version: '3.8'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  mysql-data:


services:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./src/main/resources/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  mindswap-app-mysql:
    image: app_service
    container_name: mindswap-app-2
    depends_on:
      mindswap-mysql:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      SPRING_DATA_SOURCE: com.mysql.cj.jdbc.Driver
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: ${DB_HOST}
      SERVER_PORT: '8080'
      HIBERNATE_DDL_AUTO: 'none'
      SPRING_PROFILES_ACTIVE: 'docker'
    networks:
      - mindswap-net

  mindswap-mysql:
    image: mysql
    container_name: mindswap-mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=mypass --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - mindswap-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

networks:
  mindswap-net:
    driver: bridge